operation: prod

server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Finthepen!0102
    url: jdbc:mysql://finthepen-database.crcicmakykrx.ap-northeast-2.rds.amazonaws.com:3306/fin_the_pen?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul

  security:
    user:
      password: 1

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: doc.html            # Swagger UI 경로 => localhost:8000/doc.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

  packages-to-scan: project.fin_the_pen.finClient
