#operation: local
#
#server:
#  port: 8080

#h2 DB
#spring:
#  disabled: true
#
#  packages-to-scan: project.fin_the_pen.finClient

#h2 DB
spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/fin_the_pen
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    user:
      password: 1
    oauth2:
      client:
        registration:
          kakao:
            client-id: 58044d766e3a6a856f75bd256d28a073
            client-secret: J7UYWTOODX58Up3ilLUb5U7HxaL7LVoK
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao/1107979
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao
            client-authentication-method: POST
          naver:
            client-id: SxhQhNoooSBYAzq1XRno
            client-secret: 7KEyxFXbyg
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id





springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: doc.html            # Swagger UI 경로 => localhost:8000/doc.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

  packages-to-scan: project.fin_the_pen.finClient


