version: "3"

services:
  finthepen-dev-db:
    container_name: finthepen-dev-db
    image: mysql:8.0.34
    restart: no
    volumes:
      - mysql-dev-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Finthepen
      - MYSQL_DATABASE=fin_the_pen
    ports:
      - "3307:3306"
    networks:
      - finthepen-dev-network

  finthepen-dev-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finthepen-dev-server
    restart: no
    volumes:
      - finthepen-dev-volume:/var/log
    ports:
      - "8082:8080"
    networks:
      - finthepen-dev-network
    depends_on:
      - finthepen-dev-db

#  finthepen-dev-client:
#    build:
#      context: /Users/taeyang/git/fin-the-pen-web
#      dockerfile: Dockerfile
#    container_name: finthepen-dev-client
#    restart: no
#    ports:
#      - "5174:5174"
#    networks:
#        - finthepen-dev-network
#    command: ["sh", "-c", "yarn install && yarn dev --host 0.0.0.0"]

networks:
  finthepen-dev-network:
    driver: bridge

volumes:
  mysql-dev-volume:
    driver: local
  finthepen-dev-volume:
    driver: local
