version: "3"

services:
  finthepen-db:
    container_name: finthepen-db
    image: mysql:8.0.34
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=finthepen!0102  # root 비밀번호 설정
      - MYSQL_DATABASE=fin_the_pen
    ports:
      - "3307:3306"
    networks:
      - finthepen-network

  finthepen-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finthepen-server
    restart: always
    volumes:
      - finthepen-volume:/var/log
    ports:
      - "8083:8080"
    networks:
      - finthepen-network
    depends_on:
      - finthepen-db
    environment:
#      - DATABASE_URL=jdbc:mysql://finthepen-db:3306/fin_the_pen
#      - DATABASE_USERNAME=finthepen
#      - DATABASE_PASSWORD=finthepen!0102
      - SPRING_PROFILES_ACTIVE=dev
    image: finthepen-server-image

networks:
  finthepen-network:
    driver: bridge

volumes:
  mysql-volume:
    driver: local
  finthepen-volume:
    driver: local
