# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Finthepen CI/CD branche develop

on:
  push:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Jdk 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' 
    - name: list file fin_the_pen
      run: ls -al
        
    - name: Grand execute permission for graldew
      run: chmod +x fin_the_pen/gradlew
      
    - name: Build with Gradle
      run: cd fin_the_pen; ls -al; ./gradlew clean bootjar -x test -Pprofile=prod
    - name: Find jar file
      run: cd fin_the_pen/build/libs; ls -al

    - name: CD to Ec2 instance
      uses: tiyee/action-ssh@v1.0.1
      with:
        host: ec2-43-202-60-242.ap-northeast-2.compute.amazonaws.com
        username: ec2-user
        key: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAhwgPvurG7FXj92CI3TBZgDP+p/eBq52LwQNHDWg+tuenTcW8
UDlWlwdDXdaSMROTTnM2Gz0hruO0jHEKxIke3tMcq6OyGU6q2pp9Bc6tSU/rNuXg
MRalAhrtMLGw/Z8o0iERW/zlMIZkZwLtf5G8/9dadKDldhimlk6Wn1NDScRwwT+8
hHpRQ1TzJv8/6BIjme17Vwv0wOKh38qPvh9UyvJ6Zp0WzleRFS5lzT/FRBLZsY+4
FHPVjyTlu3iw1M7ANkAtuYgHJyRQ8adezDln/CBu7SaE8JZLqH3UxEMx7fBLTbFu
4e/SgHFXWuK39TpzW6ZUHyxpQxNeHpxCRGUNBwIDAQABAoIBAF6jO8Xm7jw9hmSe
d83uUQwVZOl8Apmw9X31OhsfcLTobs2HRJBFX3bCVGi0NgnHWnqlLMqycaUNWkEE
CTPtloE9HN7+/5fVFtHXbMBhNfon1QbI3fQJluR+0rZKE23t2sJLAsuh10/HIR9B
YgsCrZ/x4yfSjH/UjwzRT6eix4ou516U/rTbYz+RvqZmU9hGWS+Qp7oJ74bi97e8
eJa5uPovFNOHY3BgIxsrSpM4vwJ7sC3RNQRUigngeldUiQgrCysZXUyPMv6x38dI
Q7+5nIB2b/jwXENii2bBjTTkjTEpebMJbqjwM6gRMrHuiB2Yc0dLGC7LFClP1w6C
iEaGPMECgYEA2zfgp2k0IWPAaS0Lu5Zvp4Qm4KQq9kKo2hmvb/aSK4K9/fPuC2Qg
nmMD5QpwbQayD+YNmTINtUSjcQuVqFP0xY0roVk9zwPTPDG8bBP4vEq78RxHOvNa
1zKH36dop8qFP6aox7a71sc3043ZKAxRZXFieHIp2WZ6LY3z10xSnb8CgYEAnbAY
AKcclg1BNu5aXjn9s/FWYZEjmW46JRSrGInZ/Mi6ham/ke/pv1W482d0INJUlCXK
YaVT1P3HUs0v7C+t4rotObMs8zHkXNG1P2kaGeE3/ZXWGOZMbWLqoeYF+ojF91FR
oi8cXu33k5yyj2srh5iiV550zSUv5NeWhc4OcrkCgYEAuW5Orc2jtwq120GrRwY9
dCmo6SR04tIIGlTXvZGImx2AsKwBk8kiflerF7b42oBrZl9m6UsZpVdmGV1/Pl+m
EOUVHupqCg5mQ+ieRZ2vLTbaO118MzVeheHMZTcqo6P/ipPi+Oxtf4QMiPrX0bR5
taFvdgq7s5Wni5kjxd5dk+kCgYBVL2gIEj7zIL32OtU+yf0wVFPh6VJd9Jocpgm3
++BzGs0IoCcJY53W6yw68cxeXsGqNrAaCAI9scsYBBi7cxZwwTrlTNIfnvhK3E8Z
rmGXUX+50lQSp3bqMOGoDGd2bKTlclyzTNf6wHtalvAvYinl2qL4ynU2zbwN2BlM
t4A+oQKBgQC+6Zfs2yqozGaByk8nXrdKYNFEd7qHUijXSyYHGNQ4iYDXt7w4DpZJ
e0fF57jN+XXEGzO2HVo1quNUNbIdC8geHduwu9afwV7/tp6075tYU2NzJl3k+w0Y
JCVXVkm/914dHhQdM5C8gU7UihUJPmYZfTSysjPo3++ck2i6uxMgmA==
-----END RSA PRIVATE KEY-----
        prot: 22
        script:
