# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Finthepen CI/CD branche develop

on:
  push:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Jdk 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' 
    - name: list file fin_the_pen
      run: ls -al
        
    - name: Grand execute permission for graldew
      run: chmod +x fin_the_pen/gradlew
      
    - name: Build with Gradle
      run: cd fin_the_pen; ls -al; ./gradlew clean bootjar -x test -Pprofile=prod
    - name: Find jar file
      run: cd fin_the_pen/build/libs; ls -al

    - name: test Binding
      run: echo "${{ secrets.EC2_HOST}}"; echo "${{ secrets.EC2_USERNAME}}"; echo "${{ secrets.EC2_SSH_KEY}}"

    # - name: CD to Ec2 instance
    #   uses: tiyee/action-ssh@v1.0.1
    #   with:
    #     host: ec2-43-202-60-242.ap-northeast-2.compute.amazonaws.com
    #     username: ec2-user
    #     prot: 22
      
